export const fleetCars = [
  {
    id: 1,
    name: 'Hyundai i10',
    brand: 'Hyundai',
    model: 'i10',
    year: '2015-2019',
    yearRange: '2015-2019',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 1899,
    images: ['/cars/i10.jpg'],
    description: 'Easy to drive and fuel-efficient, ideal for short trips and city driving.',
    features: ['Air Conditioning', 'Power Steering', 'USB Charging', 'Spacious Cabin'],
    availability: true,
    security_deposit: 3000,
    rating: 4.5,
    reviews_count: 112,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 2,
    name: 'Maruti Celerio',
    brand: 'Maruti',
    model: 'Celerio',
    year: '2014-2016',
    yearRange: '2014-2016',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 1899,
    images: ['/cars/celerio.jpg'],
    description: 'Compact hatchback with nimble handling and low running costs.',
    features: ['Power Windows', 'Air Conditioning', 'FM Radio', 'Fuel Efficient'],
    availability: true,
    security_deposit: 3000,
    rating: 4.4,
    reviews_count: 95,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 3,
    name: 'Maruti Swift',
    brand: 'Maruti',
    model: 'Swift',
    year: '2008-2011',
    yearRange: '2008-2011',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 1899,
    images: ['/cars/swift-2008.jpg'],
    description: 'Popular hatchback known for its sporty drive and reliable performance.',
    features: ['Air Conditioning', 'Central Locking', 'Power Steering', 'Compact Design'],
    availability: true,
    security_deposit: 3000,
    rating: 4.3,
    reviews_count: 104,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 4,
    name: 'Honda Amaze',
    brand: 'Honda',
    model: 'Amaze',
    year: '2014-2017',
    yearRange: '2014-2017',
    category: 'Sedan',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 1999,
    images: ['/cars/amaze.jpg'],
    description: 'Comfortable sedan with spacious seating and smooth highway performance.',
    features: ['Comfort Seats', 'Air Conditioning', 'Power Windows', 'Large Boot'],
    availability: true,
    security_deposit: 3000,
    rating: 4.5,
    reviews_count: 98,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 5,
    name: 'Toyota Etios Liva',
    brand: 'Toyota',
    model: 'Etios Liva',
    year: '2012-2016',
    yearRange: '2012-2016',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 1999,
    images: ['/cars/etios-liva.jpg'],
    description: 'Reliable hatchback with a roomy cabin and Toyota build quality.',
    features: ['Air Conditioning', 'Power Steering', 'Good Boot Space', 'Eco-friendly'],
    availability: true,
    security_deposit: 3000,
    rating: 4.4,
    reviews_count: 89,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 6,
    name: 'Maruti Swift',
    brand: 'Maruti',
    model: 'Swift',
    year: '2011-2015',
    yearRange: '2011-2015',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 1999,
    images: ['/cars/swift-2011.jpg'],
    description: 'Classic Swift with a sporty character, great for quick city driving.',
    features: ['Sporty Design', 'Air Conditioning', 'Power Steering', 'Efficient Engine'],
    availability: true,
    security_deposit: 3000,
    rating: 4.5,
    reviews_count: 107,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 7,
    name: 'Toyota Etios',
    brand: 'Toyota',
    model: 'Etios',
    year: '2012-2016',
    yearRange: '2012-2016',
    category: 'Sedan',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2199,
    images: ['/cars/etios.jpg'],
    description: 'Reliable sedan with a smooth ride and Toyota’s trusted engineering.',
    features: ['Air Conditioning', 'Spacious Interior', 'Power Steering', 'Safety Features'],
    availability: true,
    security_deposit: 3500,
    rating: 4.4,
    reviews_count: 93,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 8,
    name: 'Maruti Swift',
    brand: 'Maruti',
    model: 'Swift',
    year: '2015-2017',
    yearRange: '2015-2017',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2500,
    images: ['/cars/swift-2015.jpg'],
    description: 'Updated Swift variant with stylish looks and refined performance.',
    features: ['Touchscreen Audio', 'Air Conditioning', 'Power Steering', 'Safety Belt'],
    availability: true,
    security_deposit: 3500,
    rating: 4.5,
    reviews_count: 110,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 9,
    name: 'Maruti Baleno',
    brand: 'Maruti',
    model: 'Baleno',
    year: '2015-2018',
    yearRange: '2015-2018',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2500,
    images: ['/cars/baleno.jpg'],
    description: 'Premium hatchback with a spacious cabin and comfortable ride.',
    features: ['Cruise Control', 'Air Conditioning', 'Touchscreen Music System', 'LED Headlamps'],
    availability: true,
    security_deposit: 3500,
    rating: 4.6,
    reviews_count: 128,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 10,
    name: 'Maruti Ciaz',
    brand: 'Maruti',
    model: 'Ciaz',
    year: '2017-2018',
    yearRange: '2017-2018',
    category: 'Sedan',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2599,
    images: ['/cars/ciaz.jpg'],
    description: 'Spacious sedan crafted for comfortable long-distance travel.',
    features: ['Cruise Control', 'Leather Seats', 'Air Conditioning', 'Large Boot'],
    availability: true,
    security_deposit: 3500,
    rating: 4.5,
    reviews_count: 101,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 11,
    name: 'Maruti Swift',
    brand: 'Maruti',
    model: 'Swift',
    year: '2018-2023',
    yearRange: '2018-2023',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2790,
    images: ['/cars/swift-2018.jpg'],
    description: 'Latest Swift generation with refined styling and modern comfort.',
    features: ['Touchscreen Display', 'Air Conditioning', 'Power Steering', 'ABS'],
    availability: true,
    security_deposit: 3500,
    rating: 4.7,
    reviews_count: 134,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 12,
    name: 'Honda City',
    brand: 'Honda',
    model: 'City',
    year: '2015-2016',
    yearRange: '2015-2016',
    category: 'Sedan',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2699,
    images: ['/cars/city.jpg'],
    description: 'Elegant sedan with excellent comfort, ideal for business and leisure travel.',
    features: ['Climate Control', 'Power Windows', 'Cruise Control', 'Spacious Interior'],
    availability: true,
    security_deposit: 3500,
    rating: 4.6,
    reviews_count: 120,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 13,
    name: 'Renault Duster',
    brand: 'Renault',
    model: 'Duster',
    year: '2014-2019',
    yearRange: '2014-2019',
    category: 'SUV',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2499,
    images: ['/cars/duster.jpg'],
    description: 'Rugged SUV with strong road presence and smooth touring capability.',
    features: ['High Ground Clearance', 'Alloy Wheels', 'Air Conditioning', 'Comfort Seats'],
    availability: true,
    security_deposit: 4000,
    rating: 4.5,
    reviews_count: 118,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 14,
    name: 'Hyundai Verna',
    brand: 'Hyundai',
    model: 'Verna',
    year: '2012-2019',
    yearRange: '2012-2019',
    category: 'Sedan',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2499,
    images: ['/cars/verna.jpg'],
    description: 'Premium sedan with refined styling and a comfortable ride experience.',
    features: ['Cruise Control', 'Touchscreen Audio', 'Air Conditioning', 'Safety Airbags'],
    availability: true,
    security_deposit: 4000,
    rating: 4.6,
    reviews_count: 122,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 15,
    name: 'Hyundai i20',
    brand: 'Hyundai',
    model: 'i20',
    year: '2018-2023',
    yearRange: '2018-2023',
    category: 'Hatchback',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2699,
    images: ['/cars/i20.jpg'],
    description: 'Modern hatchback with premium features and a spacious interior.',
    features: ['Touchscreen Display', 'Air Conditioning', 'Rear Camera', 'Stylish Design'],
    availability: true,
    security_deposit: 4000,
    rating: 4.6,
    reviews_count: 115,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 16,
    name: 'Maruti Brezza',
    brand: 'Maruti',
    model: 'Brezza',
    year: '2015-2019',
    yearRange: '2015-2019',
    category: 'SUV',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Diesel',
    price_per_day: 2799,
    images: ['/cars/brezza.jpg'],
    description: 'Compact SUV offering a good balance of comfort, space and city performance.',
    features: ['High Ground Clearance', 'Air Conditioning', 'Power Steering', 'Spacious Cabin'],
    availability: true,
    security_deposit: 4000,
    rating: 4.5,
    reviews_count: 108,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 17,
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    model: 'Creta',
    year: '2015-2020',
    yearRange: '2015-2020',
    category: 'SUV',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 2990,
    images: ['/cars/creta.jpg'],
    description: 'Popular SUV with a commanding road presence and comfortable driving experience.',
    features: ['Touchscreen Audio', 'Air Conditioning', 'Reverse Camera', 'Stylish Exterior'],
    availability: true,
    security_deposit: 4500,
    rating: 4.6,
    reviews_count: 130,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 18,
    name: 'Mahindra Thar',
    brand: 'Mahindra',
    model: 'Thar',
    year: '2022-2023',
    yearRange: '2022-2023',
    category: 'SUV',
    seats: 5,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    price_per_day: 4999,
    images: ['/cars/thar.jpg'],
    description: 'Adventurous SUV built for rugged terrain and memorable road trips.',
    features: ['All Wheel Drive', 'Convertible Roof', 'Offroad Capable', 'Spacious Cargo Area'],
    availability: true,
    security_deposit: 6000,
    rating: 4.8,
    reviews_count: 145,
    created_at: '2026-06-16T00:00:00Z',
    featured: true,
  },
  {
    id: 19,
    name: 'Toyota Innova',
    brand: 'Toyota',
    model: 'Innova',
    year: '2008-2011',
    yearRange: '2008-2011',
    category: 'SUV',
    seats: 7,
    transmission: 'Manual',
    fuel_type: 'Diesel',
    price_per_day: 2599,
    images: ['/cars/innova-2008.jpg'],
    description: 'Reliable 7-seater MPV with comfortable seating for family and group travel.',
    features: ['Large Cabin', 'Air Conditioning', 'Comfort Seats', 'Ample Storage'],
    availability: true,
    security_deposit: 5000,
    rating: 4.5,
    reviews_count: 126,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 20,
    name: 'Toyota Innova',
    brand: 'Toyota',
    model: 'Innova',
    year: '2012-2016',
    yearRange: '2012-2016',
    category: 'SUV',
    seats: 7,
    transmission: 'Manual',
    fuel_type: 'Diesel',
    price_per_day: 2999,
    images: ['/cars/innova-2012.jpg'],
    description: 'Spacious and dependable 7-seater designed for long journeys and family comfort.',
    features: ['Comfort Seating', 'Air Conditioning', 'Large Boot', 'Audio System'],
    availability: true,
    security_deposit: 5000,
    rating: 4.6,
    reviews_count: 132,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 21,
    name: 'Maruti Ertiga',
    brand: 'Maruti',
    model: 'Ertiga',
    year: '2010-2015',
    yearRange: '2010-2015',
    category: 'SUV',
    seats: 7,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    price_per_day: 3099,
    images: ['/cars/ertiga.jpg'],
    description: 'Comfortable 7-seater MPV with flexible seating and good city usability.',
    features: ['Automatic Transmission', 'Air Conditioning', 'Spacious Interior', 'Rear AC Vents'],
    availability: true,
    security_deposit: 5000,
    rating: 4.4,
    reviews_count: 96,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 22,
    name: 'Mahindra XUV500 W8',
    brand: 'Mahindra',
    model: 'XUV500 W8',
    year: '2015-2019',
    yearRange: '2015-2019',
    category: 'SUV',
    seats: 7,
    transmission: 'Manual',
    fuel_type: 'Diesel',
    price_per_day: 3499,
    images: ['/cars/xuv500-w8.jpg'],
    description: 'Strong SUV with robust handling and comfortable 7-seat layout.',
    features: ['SUV Styling', 'Air Conditioning', 'Power Steering', 'Spacious Cabin'],
    availability: true,
    security_deposit: 5500,
    rating: 4.5,
    reviews_count: 118,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 23,
    name: 'Mahindra XUV500 W10',
    brand: 'Mahindra',
    model: 'XUV500 W10',
    year: '2016-2019',
    yearRange: '2016-2019',
    category: 'SUV',
    seats: 7,
    transmission: 'Automatic',
    fuel_type: 'Diesel',
    price_per_day: 3999,
    images: ['/cars/xuv500-w10.jpg'],
    description: 'Premium SUV variant with upgraded features and comfortable ride.',
    features: ['Automatic Transmission', 'Touchscreen Audio', 'Air Conditioning', 'Rear Parking Sensors'],
    availability: true,
    security_deposit: 5500,
    rating: 4.6,
    reviews_count: 112,
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 24,
    name: 'Toyota Fortuner',
    brand: 'Toyota',
    model: 'Fortuner',
    year: '2010-2015',
    yearRange: '2010-2015',
    category: 'SUV',
    seats: 7,
    transmission: 'Automatic',
    fuel_type: 'Diesel',
    price_per_day: 4299,
    images: ['/cars/fortuner.jpg'],
    description: 'Strong SUV with commanding road presence and premium family comfort.',
    features: ['Automatic Transmission', 'Leather Seats', 'Air Conditioning', 'Ample Cabin Space'],
    availability: true,
    security_deposit: 6000,
    rating: 4.7,
    reviews_count: 142,
    created_at: '2026-06-16T00:00:00Z',
    featured: true,
  },
  {
    id: 25,
    name: 'Toyota Innova Crysta',
    brand: 'Toyota',
    model: 'Innova Crysta',
    year: '2016-2020',
    yearRange: '2016-2020',
    category: 'Premium Luxury',
    seats: 7,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    price_per_day: 4799,
    images: ['/cars/innova-crysta.jpg'],
    description: 'Premium 7-seater MPV designed for luxury travel and executive comfort.',
    features: ['Automatic Transmission', 'Leather Seats', 'Rear AC', 'Touchscreen Infotainment'],
    availability: true,
    security_deposit: 7000,
    rating: 4.8,
    reviews_count: 158,
    created_at: '2026-06-16T00:00:00Z',
    featured: true,
  },
  {
    id: 26,
    name: 'Toyota Innova Hycross',
    brand: 'Toyota',
    model: 'Innova Hycross',
    year: '2020-2026',
    yearRange: '2020-2026',
    category: 'Premium Luxury',
    seats: 7,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    price_per_day: 7499,
    images: ['/cars/innova-hycross.jpg'],
    description: 'Top-tier premium MPV with the latest comfort, safety and luxury features.',
    features: ['Automatic Transmission', 'Premium Interior', 'Rear Climate Control', 'Infotainment System'],
    availability: true,
    security_deposit: 9000,
    rating: 4.9,
    reviews_count: 175,
    created_at: '2026-06-16T00:00:00Z',
    featured: true,
  },
  {
    id: 27,
    name: 'Toyota Fortuner Legender',
    brand: 'Toyota',
    model: 'Fortuner Legender',
    year: '2021-2023',
    yearRange: '2021-2023',
    category: 'Premium Luxury',
    seats: 7,
    transmission: 'Automatic',
    fuel_type: 'Diesel',
    price_per_day: 11999,
    images: ['/cars/fortuner-legender.jpg'],
    description: 'Premium SUV designed for premium travel with executive comfort and space.',
    features: ['Automatic Transmission', 'Premium Upholstery', 'Advanced Safety Systems', 'Luxury Ride'],
    availability: true,
    security_deposit: 12000,
    rating: 4.9,
    reviews_count: 160,
    created_at: '2026-06-16T00:00:00Z',
  },
];

